# Generated by Django 5.2.6 on 2025-10-13 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_analysis', 'В анализе'), ('optimized', 'Оптимизирован'), ('ignored', 'Игнорирован')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('problem_pattern', models.CharField(blank=True, max_length=200, verbose_name='Паттерн проблемы')),
                ('analysis_notes', models.TextField(blank=True, verbose_name='Заметки анализа')),
                ('optimized_query', models.TextField(blank=True, verbose_name='Оптимизированный запрос')),
                ('expected_improvement', models.FloatField(blank=True, null=True, verbose_name='Ожидаемое улучшение (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('query_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.querylog', verbose_name='Лог запроса')),
            ],
            options={
                'verbose_name': 'Медленный запрос',
                'verbose_name_plural': 'Медленные запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
