# Generated by Django 5.2.6 on 2025-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slowquery',
            name='problem_pattern',
        ),
        migrations.AddField(
            model_name='slowquery',
            name='actual_improvement',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическое улучшение (%)'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='after_duration_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность после (мс)'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало анализа'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='before_duration_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность до (мс)'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='optimization_notes',
            field=models.TextField(blank=True, verbose_name='Объяснение оптимизации'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='optimized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время оптимизации'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='problem_category',
            field=models.CharField(blank=True, choices=[('full_scan', '📊 Полносканирование таблицы'), ('missing_index', '📈 Отсутствие индекса'), ('cross_join', '❌ CROSS JOIN'), ('subquery', '🔄 Неоптимизированный подзапрос'), ('large_result', '💾 Большой результат'), ('memory_usage', '🧠 Высокое использование памяти'), ('network', '🌐 Сетевые проблемы'), ('configuration', '⚙️ Проблема конфигурации'), ('other', '❓ Другое')], max_length=20, verbose_name='Категория проблемы'),
        ),
        migrations.AddField(
            model_name='slowquery',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='slowquery',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Новый'), ('in_analysis', '🔍 В анализе'), ('waiting_feedback', '⏳ Ожидает фидбека'), ('optimized', '✅ Оптимизирован'), ('ignored', '❌ Игнорирован'), ('cannot_optimize', '🚫 Не подлежит оптимизации')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
