# Generated by Django 5.2.6 on 2025-10-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        ('query_lab', '0002_remove_slowquery_problem_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_score', models.IntegerField(default=0, verbose_name='Оценка сложности')),
                ('has_full_scan', models.BooleanField(default=False, verbose_name='Полносканирование')),
                ('has_sorting', models.BooleanField(default=False, verbose_name='Сортировка')),
                ('has_aggregation', models.BooleanField(default=False, verbose_name='Агрегация')),
                ('pipeline_complexity', models.IntegerField(default=0, verbose_name='Сложность pipeline')),
                ('table_stats', models.JSONField(default=dict, verbose_name='Статистика таблиц')),
                ('recommendations', models.JSONField(default=list, verbose_name='Рекомендации')),
                ('warnings', models.JSONField(default=list, verbose_name='Предупреждения')),
                ('explain_plan', models.JSONField(default=list, verbose_name='EXPLAIN PLAN')),
                ('explain_pipeline', models.JSONField(default=list, verbose_name='EXPLAIN PIPELINE')),
                ('estimated_improvement', models.FloatField(blank=True, null=True, verbose_name='Ожидаемое улучшение (%)')),
                ('analysis_duration_ms', models.FloatField(default=0, verbose_name='Время анализа (мс)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время анализа')),
                ('analysis_version', models.CharField(default='1.0', max_length=20, verbose_name='Версия анализа')),
                ('query_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.querylog', verbose_name='Лог запроса')),
            ],
            options={
                'verbose_name': 'Результат анализа запроса',
                'verbose_name_plural': 'Результаты анализа запросов',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='TableAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200, verbose_name='Название таблицы')),
                ('database', models.CharField(default='default', max_length=100, verbose_name='База данных')),
                ('total_rows', models.BigIntegerField(default=0, verbose_name='Всего строк')),
                ('total_bytes', models.BigIntegerField(default=0, verbose_name='Размер в байтах')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Движок')),
                ('partition_key', models.TextField(blank=True, verbose_name='Ключ партиционирования')),
                ('sorting_key', models.TextField(blank=True, verbose_name='Ключ сортировки')),
                ('query_count', models.IntegerField(default=0, verbose_name='Количество запросов')),
                ('avg_duration_ms', models.FloatField(default=0, verbose_name='Среднее время выполнения')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='Последний анализ')),
                ('table_recommendations', models.JSONField(default=list, verbose_name='Рекомендации для таблицы')),
            ],
            options={
                'verbose_name': 'Анализ таблицы',
                'verbose_name_plural': 'Анализ таблиц',
                'indexes': [models.Index(fields=['table_name', 'database'], name='query_lab_t_table_n_6402fb_idx'), models.Index(fields=['total_rows'], name='query_lab_t_total_r_89a190_idx')],
                'unique_together': {('table_name', 'database')},
            },
        ),
        migrations.CreateModel(
            name='IndexRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200, verbose_name='Название колонки')),
                ('index_type', models.CharField(default='skip', max_length=50, verbose_name='Тип индекса')),
                ('recommendation_reason', models.TextField(verbose_name='Причина рекомендации')),
                ('expected_improvement', models.FloatField(blank=True, null=True, verbose_name='Ожидаемое улучшение (%)')),
                ('analysis_source', models.CharField(choices=[('explain', 'EXPLAIN анализ'), ('query_log', 'Query Log статистика'), ('manual', 'Ручная рекомендация')], default='explain', max_length=20)),
                ('query_count', models.IntegerField(default=0, verbose_name='Количество запросов')),
                ('avg_filter_selectivity', models.FloatField(blank=True, null=True, verbose_name='Селективность фильтра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('implemented', models.BooleanField(default=False, verbose_name='Реализовано')),
                ('implemented_at', models.DateTimeField(blank=True, null=True, verbose_name='Время реализации')),
                ('table_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_lab.tableanalysis', verbose_name='Анализ таблицы')),
            ],
            options={
                'verbose_name': 'Рекомендация индекса',
                'verbose_name_plural': 'Рекомендации индексов',
                'ordering': ['-expected_improvement'],
            },
        ),
    ]
