# Generated by Django 5.2.6 on 2025-12-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_lab', '0003_queryanalysisresult_tableanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slowquery',
            name='optimized_query_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хеш оптимизированного запроса'),
        ),
    ]
