# Generated by Django 5.2.6 on 2025-10-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHouseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название инстанса')),
                ('host', models.CharField(max_length=200, verbose_name='Хост')),
                ('port', models.IntegerField(default=8123, verbose_name='Порт')),
                ('database', models.CharField(default='default', max_length=100, verbose_name='База данных')),
                ('username', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный мониторинг')),
                ('slow_query_threshold_ms', models.IntegerField(default=1000, verbose_name='Порог медленных запросов (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инстанс ClickHouse',
                'verbose_name_plural': 'Инстансы ClickHouse',
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=255, verbose_name='ID запроса')),
                ('query_text', models.TextField(verbose_name='Текст запроса')),
                ('normalized_query_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш нормализованного запроса')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('duration_ms', models.FloatField(verbose_name='Время выполнения (мс)')),
                ('read_rows', models.BigIntegerField(default=0, verbose_name='Прочитано строк')),
                ('read_bytes', models.BigIntegerField(default=0, verbose_name='Прочитано байт')),
                ('memory_usage', models.BigIntegerField(default=0, verbose_name='Использовано памяти')),
                ('query_start_time', models.DateTimeField(verbose_name='Время начала запроса')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сбора')),
                ('is_slow', models.BooleanField(db_index=True, default=False, verbose_name='Медленный запрос')),
                ('is_initial', models.BooleanField(default=True, verbose_name='Изначальный запрос')),
                ('clickhouse_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.clickhouseinstance', verbose_name='Инстанс')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
                'ordering': ['-query_start_time'],
                'indexes': [models.Index(fields=['collected_at'], name='monitor_que_collect_90d5e2_idx'), models.Index(fields=['normalized_query_hash', 'collected_at'], name='monitor_que_normali_764572_idx')],
            },
        ),
    ]
