# Generated by Django 5.2.6 on 2025-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAGMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255, verbose_name='DAG ID')),
                ('schedule', models.CharField(blank=True, max_length=255, verbose_name='Расписание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_paused', models.BooleanField(verbose_name='На паузе')),
                ('fileloc', models.CharField(max_length=500, verbose_name='Путь к файлу DAG')),
                ('last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('created_at', models.DateTimeField(verbose_name='Время фиксации')),
                ('lineage', models.JSONField(default=dict, verbose_name='Lineage (JSON)')),
            ],
            options={
                'verbose_name': 'Метаданные DAG',
                'verbose_name_plural': 'Метаданные DAG-ов',
                'db_table': 'data_registry_dagmetadata',
                'ordering': ['-created_at'],
                'unique_together': {('dag_id', 'created_at')},
            },
        ),
    ]
